### ISSUE TITLE
Sample "SPA_WebAPI_Client" - can't login anymore

### ISSUE THREAD

**Issue by SCullman** [intelequia/dnn.azureadb2cprovider#14]
I try to get the ""SPA_WebAPI_Client" running, but when I set App ID Uri and Scopes 
![image](https://user-images.githubusercontent.com/5693190/71742070-d5631500-2e60-11ea-825e-6ea21e93123c.png),
login will fail with 
![image](https://user-images.githubusercontent.com/5693190/71742132-0e9b8500-2e61-11ea-8fbc-080574740e1a.png)  

 The Azure AD B2C application from  generael settings has been given access to the demoapi and the read / write scope.

Whether JWT is enabled or not doesn't change anything. Shall I set the id of the web api here? If I do, I monitor an additional call to `https://<tenant>.b2clogin.com/<TenantId>/oauth2/v2.0/authorize?scope=demoapi/read%20demoapi/write&client_id=<Azure AD B2C application Id>&redirect_uri=https%3a%2f%mysite%2fLogin&state=s%3dAzureB2C%3bp%3d0%3bc%3den-US&response_type=code&response_mode=query&p=B2C_1_signupsignin1`

Sample active-directory-b2c-dotnet-webapp-and-webapi is up and running.

If I remove both App Id Uri and Scopes, login works again, but of course then I am not authorized to use the SPA WebApi Client.

Am I doing something wrong or is this a bug?

**Comment by davidjrh** [comment]
Hi @SCullman, 

Can you set the APIUrl to https://<tenant>.onmicrosoft.com/demoapi/ and see if that works?

**Comment by SCullman** [comment]
@davidjrh , if I do it the way you write here (and of course the way it is written in the help text), it works all of a sudden.
